---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.13-bookworm

inputs:
  - name: dp-frontend-dataset-controller
    path: dp-frontend-dataset-controller

outputs:
  - name: build

run:
  path: dp-frontend-dataset-controller/ci/scripts/build.sh
