---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tags: 1.9.0

inputs:
  - name: dp-frontend-dataset-controller
    path: go/src/github.com/ONSdigital/dp-frontend-dataset-controller

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-frontend-dataset-controller/ci/scripts/build.sh
